In [2]:
import pandas as pd

In [11]:
business_csv = r"C:\Users\Loe Hui Lin\Desktop\Personal_Projects\Udemy_Data_Analysis\business_courses.csv"
# original dataset: 10 columns and 1194 rows
# after initial preprocessing: 12 columns and 1193 rows

In [13]:
# specify encoding because Pandas is unable to decode a byte in the csv file using UTF-8 encoding
business_df = pd.read_csv(business_csv, encoding='latin1')
business_df

,course_id,course_title,price,free_or_paid,num_subscribers,num_reviews,num_lectures,level,Rating,content_duration,published_timestamp_date,published_timestamp_time
0,49798,Bitcoin or How I Learned to Stop Worrying and ...,0,Free,65576,936,24,All Levels,0.56,8.0,4/20/2013,02:25:22Z
1,48841,Accounting in 60 Minutes - A Brief Introduction,0,Free,56659,4397,16,Beginner Level,0.95,1.5,4/7/2013,21:39:25Z
2,133536,Stock Market Investing for Beginners,0,Free,50855,2698,15,All Levels,0.91,1.5,12/25/2013,19:53:34Z
3,151668,Introduction to Financial Modeling,0,Free,29167,1463,8,All Levels,0.18,1.5,5/27/2014,16:22:16Z
4,648826,The Complete Financial Analyst Course 2017,195,Paid,24481,2347,174,All Levels,0.37,10.0,1/21/2016,01:38:48Z
...,...,...,...,...,...,...,...,...,...,...,...,...
1186,885413,Foundations of Investing,40,Paid,0,0,18,Beginner Level,0.95,2.0,7/27/2016,21:07:46Z
1187,1231958,60 Minutes to Fundamental Accounting Skills,75,Paid,0,0,9,All Levels,0.95,2.5,6/28/2017,21:55:29Z
1188,1057040,Teeter-Totter Accounting,90,Paid,0,0,12,Intermediate Level,0.36,1.0,2/8/2017,22:15:56Z
1189,1258666,Financial Statement Auditing Cycles,50,Paid,0,0,9,All Levels,0.15,2.0,6/29/2017,23:20:10Z
1190,1232282,The Cash Flow Statement - An Introduction,50,Paid,0,0,10,All Levels,0.18,1.5,6/28/2017,16:05:51Z

In [14]:
business_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1191 entries, 0 to 1190
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   course_id                 1191 non-null   int64
 1   course_title              1191 non-null   object
 2   price                     1191 non-null   int64
 3   free_or_paid              1191 non-null   object
 4   num_subscribers           1191 non-null   int64
 5   num_reviews               1191 non-null   int64
 6   num_lectures              1191 non-null   int64
 7   level                     1191 non-null   object
 8   Rating                    1191 non-null   float64
 9   content_duration          1191 non-null   float64
 10  published_timestamp_date  1191 non-null   object
 11  published_timestamp_time  1191 non-null   object
dtypes: float64(2), int64(5), object(5)
memory usage: 111.8+ KB

In [18]:
# Assuming you've already loaded your data into a DataFrame named business_df
row_48 = business_df.iloc[47]  # iloc is zero-based indexing, so the 48th row is at index 47
print(row_48)

course_id                                                              377370
course_title                Learn to Trade the Stock Market without Blowin...
price                                                                      60
free_or_paid                                                             Paid
num_subscribers                                                          6967
num_reviews                                                                16
num_lectures                                                               34
level                                                          Beginner Level
Rating                                                                   0.48
content_duration                                                          1.0
published_timestamp_date                                             5/2/2017
published_timestamp_time                                            20:53:24Z
Name: 47, dtype: object